name: Clone Repository
on:
  push:
    branches:
      - master
jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      TERM: dumb
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: 15
      - name: Build
        run: ./gradlew check

