name: Continuos Integretion
on:
  push:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: set jdk
        uses: joschi/setup-jdk@2.3.0
        with:
          java-version: 15
      - name: Build
        run: ./gradlew build
