name: Continuos Integretion
on:
  push:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: set jdk
        uses:
          actions/checkout@v4
          actions/setup-java@v4
        with:
          java-version: 17
      - name: Build
        run: ./gradlew build
